[xm,Fs] = audioread('message.wav' );
t = linspace(0,length(xm)/Fs,length(xm));
xc = LSSB(xm,10,3000,Fs);
xc_ =USSB(xm,10,3000,Fs);
subplot(511);
plot(t,xm,'b');
xlabel('Time');
ylabel('Amplitude');
title('Message signal');
subplot(512);
plot(t,xc,'c');
xlabel('Time');
ylabel('Amplitude');
title('Modulated signal');
subplot(513);
plot(fftshift(abs(fft(xm))),'g');
xlabel('frequency');
ylabel('magnitude');
title('Fourier Transform of signal');
Xc=fft(xc);
subplot(514);
plot(fftshift(abs(Xc)),'r');
xlabel('frequency');
ylabel('magnitude');
title('Fourier Transform of Lower single side band modulation ');
subplot(515);
plot(fftshift(abs(fft(xc_))),'m');
xlabel('frequency');
ylabel('magnitude');
title('Fourier Transform of upper single side band modulation');